name: build-images-action
on:
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build_ironic_client:
    name: build ironic-client image
    uses: metal3-io/project-infra/.github/workflows/container-image-build.yml@main
    with:
      image-name: "ironic-client"
      pushImage: true
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
