name: build-images-action
on:
  push:
    branches:
      - 'main'
permissions: {}
jobs:
  build:
    name: Build container images
    runs-on: ubuntu-latest
    if: github.repository == 'metal3-io/ironic-client'
    permissions:
      contents: read
    steps:
      - name: build ironic-client image
        uses: toptal/jenkins-job-trigger-action@137fff703dd260b52b53d3ba1960396415abc568 # 1.0.2
        with:
          jenkins_url: "https://jenkins.nordix.org/"
          jenkins_user: "metal3.bot@gmail.com"
          jenkins_token: ${{ secrets.JENKINS_TOKEN }}
          job_name: "metal3_ironic-client_container_image_building"
          job_params: |
            {
              "BUILD_CONTAINER_IMAGE_GIT_REFERENCE": "${{ github.ref }}"
            }
          job_timeout: "1000"
